version: "3.7"
services:
 app:
   stdin_open: true
   tty: true
   build: .
   restart: always
   hostname: ubuntu01
  # app_image:
  #   stdin_open: true
  #   tty: true
  #   image: hardemic/monitor:v2
  #   restart: always
  #   hostname: ubuntu01
#    depends_on:
#        - db
#  db:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: example
    
