version: "3.7"
services:
  app:
    container_name: monitor
    stdin_open: true
    tty: true
    image: hardemic/monitor
    restart: always
    hostname: ubuntu01
  database:
    container_name: database
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
