version: "3.7"
services:
  app:
    container_name: monitor
    stdin_open: true
    tty: true
    image: hardemic/monitor:latest
    restart: always
    hostname: ubuntu01
    depends_on:
      - database
    networks:
      - mysql-compose-network
  database:
    container_name: database
    image: hardemic/database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    expose:
   
    - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hardemic
      MYSQL_USERNAME: docker
      MYSQL_PASSWORD: docker
    volumes:
      - mysqlvol:/var/lib/mysql
    
    networks:
      - mysql-compose-network
volumes:
  mysqlvol: {}
networks: 
  mysql-compose-network:
    driver: bridge